-- V0__Test.sql brukes til å opprette ting som finnes på GCP.
DROP ROLE IF EXISTS cloudsqliamuser;
CREATE ROLE cloudsqliamuser;

CREATE TABLE TEST
(
    ID   SERIAL NOT NULL PRIMARY KEY,
    TEST TEXT
);

CREATE TABLE TEST_BYTES
(
    TEST      BYTEA NOT NULL,
    TEST_NULL BYTEA
);

CREATE TABLE TEST_STRING
(
    TEST      TEXT NOT NULL,
    TEST_NULL TEXT
);

CREATE TABLE TEST_LONG
(
    TEST_0    BIGINT NOT NULL,
    TEST_1    BIGINT NOT NULL,
    TEST_NULL BIGINT
);

CREATE TABLE TEST_UUID
(
    TEST      UUID NOT NULL,
    TEST_NULL UUID
);

CREATE TABLE TEST_DATERANGE
(
    TEST      DATERANGE NOT NULL,
    TEST_NULL DATERANGE
);

CREATE TABLE TEST_BOOLEAN
(
    TEST_TRUE  BOOLEAN NOT NULL,
    TEST_FALSE BOOLEAN NOT NULL,
    TEST_NULL  BOOLEAN
);

CREATE TABLE TEST_LOCALDATE
(
    TEST      DATE NOT NULL,
    TEST_NULL DATE
);

CREATE TABLE TEST_LOCALDATETIME
(
    TEST      TIMESTAMP NOT NULL,
    TEST_NULL TIMESTAMP
);
