apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dokumentmottak
  namespace: aap
  labels:
    team: aap
    sub: dokumentmottak
spec:
  image: {{image}}
  # Setter utrullingsstrategi til Recreate for test. Settes til default før prodsetting
#  strategy:
#    type: Recreate
  ingresses:
      - "https://aap-dokumentmottak.intern.dev.nav.no"
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        databases:
          - name: dokumentmottak
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  secureLogs:
    enabled: true
  accessPolicy:
      rules:
        - application: tilgang
        - application: oppgavestyring
        - application: statistikk
