apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: behandlingsflyt
  namespace: aap
  labels:
    team: aap
    sub: behandlingsflyt
spec:
  image: {{image}}
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
          extra:
              - "NAVident"
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: aap-saksbehandling