apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: behandlingsflyt
  namespace: aap
  labels:
    team: aap
    sub: behandlingsflyt
spec:
  image: {{image}}
  # Setter utrullingsstrategi til Recreate for test. Settes til default før prodsetting
  strategy:
    type: Recreate
  ingresses:
      - "https://aap-behandlingsflyt.intern.dev.nav.no"
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: behandlingsflyt
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: saksbehandling
        - application: mottak
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
      rules:
        - application: yrkesskade-saker
          namespace: yrkesskade
  env:
    - name: INTEGRASJON_PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: INTEGRASJON_PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: INTEGRASJON_YRKESSKADE_URL
      value: http://yrkesskade-saker.yrkesskade/api/v1/saker/
    - name: INTEGRASJON_YRKESSKADE_SCOPE
      value: api://dev-gcp.yrkesskade.yrkesskade-saker/.default
    - name: INTEGRASJON_INSTITUSJONSOPPHOLD_URL
      value: https://institusjon-opphold-proxy-q2.dev-fss-pub.nais.io/api/v1/person/institusjonsopphold
    - name: INTEGRASJON_INSTITUSJONSOPPHOLD_SCOPE
      value: api://dev-gcp.team-rocket.institusjon-api/.default
