apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: behandlingsflyt
  namespace: aap
  labels:
    team: aap
    sub: behandlingsflyt
spec:
  image: {{image}}
  ingresses:
      - "https://aap-behandlingsflyt.intern.dev.nav.no"
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: behandlingsflyt
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: aap-saksbehandling
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
  env:
    - name: PDL_BASE_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
