apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: postmottak-backend
  namespace: aap
  labels:
    team: aap
    sub: postmottak
spec:
  image: {{image}}
  # Setter utrullingsstrategi til Recreate for test. Settes til default før prodsetting
#  strategy:
#    type: Recreate
  ingresses:
      - {{ingres}}
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: {{replicas.disableAutoScaling}}
    max: {{replicas.max}}
    min: {{replicas.min}}
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
        destinations:
            - id: elastic
            - id: loki
  azure:
      application:
          enabled: true
          allowAllUsers: true
          claims:
              extra:
                  - "NAVident"
                  - "azp_name"
  kafka:
      pool: {{kafka.pool}}
      streams: true
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: {{sql.tier}}
        diskAutoresize: {{sql.diskAutoresize}}
        highAvailability: {{sql.highAvailability}}
        pointInTimeRecovery: {{sql.pointInTimeRecovery}}
        databases:
          - name: postmottak
            envVarPrefix: DB_POSTMOTTAK
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: postmottak
        - application: paw-patrol
        {{#each inbound.rules}}
        - {{this}}
        {{/each}}
    outbound:
      external:
        {{#each outbound.external}}
             - host: {{this.host}}
        {{/each}}
      rules:
        - application: tilgang
        - application: behandlingsflyt
        - application: oppgave
        - application: api-intern
        - application: skjermede-personer-pip
          namespace: nom
  env:
  {{#each env}}
    - name: {{this.name}}
      value: this.value}}
  {{/each}}