ingres: "https://aap-postmottak-backend.intern.dev.nav.no"

sql:
  tier: db-f1-micro
  highAvailability: false
  pointInTimeRecovery: false

replicas:
  min: 1
  max: 1
  disableAutoScaling: true

kafka:
  pool: nav-dev

inbound:
  rules:
    - application: saksbehandling
    - application: saksbehandling-lokal # For lokal utvikling. IKKE kopier denne til prod.yaml
    - application: paw-patrol
    - application: azure-token-generator
      namespace: nais
      cluster: dev-gcp

outbound:
  rules:
    - application: tilgang
    - application: behandlingsflyt
    - application: oppgave
    - application: statistikk
    - application: skjermede-personer-pip
      namespace: nom
    - application: pensjon-pen-q2
      namespace: pensjon-q2
      cluster: dev-fss
  external:
    - host: saf.dev-fss-pub.nais.io
    - host: dokarkiv.dev-fss-pub.nais.io
    - host: oppgave.dev-fss-pub.nais.io
    - host: pdl-api.dev-fss-pub.nais.io
    - host: aap-fss-proxy.dev-fss-pub.nais.io
    - host: veilarbarena.dev-fss-pub.nais.io
    - host: pensjon-pen-q2.dev-fss-pub.nais.io

env:
  - name: INTEGRASJON_SAF_URL_GRAPHQL
    value: https://saf-q2.dev-fss-pub.nais.io/graphql
  - name: INTEGRASJON_SAF_URL_REST
    value: https://saf-q2.dev-fss-pub.nais.io/rest
  - name: INTEGRASJON_SAF_SCOPE
    value: api://dev-fss.teamdokumenthandtering.saf/.default
  - name: INTEGRASJON_JOARK_URL
    value: https://dokarkiv-q2.dev-fss-pub.nais.io
  - name: INTEGRASJON_JOARK_SCOPE
    value: api://dev-fss.teamdokumenthandtering.dokarkiv/.default
  - name: INTEGRASJON_AAP_FSS_PROXY_URL
    value: https://aap-fss-proxy.dev-fss-pub.nais.io
  - name: INTEGRASJON_AAP_FSS_PROXY_SCOPE
    value: api://dev-fss.aap.fss-proxy/.default
  - name: INTEGRASJON_BEHANDLINGSFLYT_URL
    value: http://behandlingsflyt
  - name: INTEGRASJON_BEHANDLINGSFLYT_SCOPE
    value: api://dev-gcp.aap.behandlingsflyt/.default
  - name: INTEGRASJON_AAP_INTERN_API_URL
    value: http://api-intern
  - name: INTEGRASJON_AAP_INTERN_API_SCOPE
    value: api://dev-gcp.aap.api-intern/.default
  - name: INTEGRASJON_OPPGAVE_URL
    value: http://oppgave
  - name: INTEGRASJON_OPPGAVE_SCOPE
    value: api://dev-gcp.aap.oppgave/.default
  - name: INTEGRASJON_STATISTIKK_URL
    value: http://statistikk
  - name: INTEGRASJON_STATISTIKK_SCOPE
    value: api://dev-gcp.aap.statistikk/.default
  - name: INTEGRASJON_TILGANG_URL
    value: http://tilgang
  - name: INTEGRASJON_TILGANG_SCOPE
    value: api://dev-gcp.aap.tilgang/.default
  - name: INTEGRASJON_OPPGAVEAPI_URL
    value: https://oppgave.dev-fss-pub.nais.io
  - name: INTEGRASJON_OPPGAVEAPI_SCOPE
    value: api://dev-fss.oppgavehandtering.oppgave/.default
  - name: GOSYS_URL
    value: https://gosys-q2.dev.intern.nav.no/gosys
  - name: INTEGRASJON_PDL_URL
    value: https://pdl-api.dev-fss-pub.nais.io
  - name: INTEGRASJON_PDL_SCOPE
    value: api://dev-fss.pdl.pdl-api/.default
  - name: INTEGRASJON_ARENA_URL
    value: https://aap-fss-proxy.dev-fss-pub.nais.io
  - name: INTEGRASJON_ARENA_SCOPE
    value: api://dev-fss.aap.fss-proxy/.default
  - name: INTEGRASJON_NORG_URL
    value: https://norg2.dev-fss-pub.nais.io
  - name: INTEGRASJON_NOM_URL
    value: http://skjermede-personer-pip.nom
  - name: INTEGRASJON_NOM_SCOPE
    value: api://dev-gcp.nom.skjermede-personer-pip/.default
  - name: INTEGRASJON_VEILARBARENA_URL
    value: https://veilarbarena.dev-fss-pub.nais.io
  - name: INTEGRASJON_VEILARBARENA_SCOPE
    value: api://dev-fss.pto.veilarbarena/.default
  - name: INTEGRASJON_PESYS_URL
    value: https://pensjon-pen-q2.dev-fss-pub.nais.io
  - name: INTEGRASJON_PESYS_SCOPE
    value: api://dev-fss.pensjon-q2.pensjon-pen-q2/.default