apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
    name: journalpost-til-arena
    namespace: aap
    labels:
        team: aap
    annotations:
        kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
    pool: nav-dev
    config:
        cleanupPolicy: delete
        minimumInSyncReplicas: 1
        partitions: 3
        replication: 2
    acl:
        - team: aap
          application: postmottak-backend
          access: write
        - team: aap
          application: aap-jfr-arena
          access: read