[versions]
komponenter = "2.0.163"
tilgang = "1.0.241"
arenaoppslag = "0.6.2"
behandlingsflyt = "0.0.663"
kafka = "8.1.1-ce"
testcontainers = "2.0.5"

[libraries]
ktor-openapi-gen = { module = "no.nav.aap.kelvin:ktor-openapi-generator", version.ref = "komponenter" }

dbconnect = { module = "no.nav.aap.kelvin:dbconnect", version.ref = "komponenter" }
verdityper = { module = "no.nav.aap.kelvin:verdityper", version.ref = "komponenter" }
dbmigrering = { module = "no.nav.aap.kelvin:dbmigrering", version.ref = "komponenter" }
httpklient = { module = "no.nav.aap.kelvin:httpklient", version.ref = "komponenter" }
infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
server = { module = "no.nav.aap.kelvin:server", version.ref = "komponenter" }
motor = { module = "no.nav.aap.kelvin:motor", version.ref = "komponenter" }
motor-api = { module = "no.nav.aap.kelvin:motor-api", version.ref = "komponenter" }
gateway = { module = "no.nav.aap.kelvin:gateway", version.ref = "komponenter" }
dbtest = { module = "no.nav.aap.kelvin:dbtest", version.ref = "komponenter" }
motor-test-utils = { module = "no.nav.aap.kelvin:motor-test-utils", version.ref = "komponenter" }
tilgang-kontrakt = { module = "no.nav.aap.tilgang:api-kontrakt", version.ref = "tilgang" }
tilgang-plugin = { module = "no.nav.aap.tilgang:plugin", version.ref = "tilgang" }
arenaoppslag-kontrakt = { module = "no.nav.aap.arenaoppslag:kontrakt", version.ref = "arenaoppslag" }
behandlingsflyt-kontrakt = { module = "no.nav.aap.behandlingsflyt:kontrakt", version.ref = "behandlingsflyt" }

avro = { module = "org.apache.avro:avro", version = "1.12.2" }
kafka-streams-avro-serde = { module = "io.confluent:kafka-streams-avro-serde", version = "8.1.1" }
teamdokumenthandtering-avro-schemas = { module = "no.nav.teamdokumenthandtering:teamdokumenthandtering-avro-schemas", version = "2.0.0" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
kafka-streams = { module = "org.apache.kafka:kafka-streams", version.ref = "kafka" }
kafka-streams-test-utils = { module = "org.apache.kafka:kafka-streams-test-utils", version.ref = "kafka" }

bekk-no-commons = { module = "no.bekk.bekkopen:nocommons", version = "0.17.0" }

testcontainers-postgres = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }