DROP TRIGGER IF EXISTS BEHANDLING_VERSJON_FK_TEMA_BUMPER_TRIGGER ON SKAL_TIL_AAP_AVKLARING;
DROP TRIGGER IF EXISTS BEHANDLING_VERSJON_FK_KATEGORI_BUMPER_TRIGGER ON KATEGORIAVKLARING;
DROP TRIGGER IF EXISTS BEHANDLING_VERSJON_FK_DIGITALISERING_BUMPER_TRIGGER ON DIGITALISERINGSAVKLARING;
DROP TRIGGER IF EXISTS BEHANDLING_VERSJON_FK_DIGITALISERING_BUMPER_TRIGGER ON SAKSNUMMER_AVKLARING;

CREATE OR REPLACE FUNCTION BEHANDLING_VERSJON_FK_BUMPER()
    RETURNS TRIGGER
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    CREATE TEMP TABLE IF NOT EXISTS UPDATE_FLAG (behandling_id BIGINT) ON COMMIT DROP;
    IF (SELECT CASE WHEN COUNT(*) = 0 then 1 else 0 end FROM UPDATE_FLAG WHERE behandling_id = new.behandling_id) THEN
        UPDATE BEHANDLING
        SET VERSJON = VERSJON + 1
        WHERE ID = NEW.BEHANDLING_ID;
        INSERT INTO UPDATE_FLAG (behandling_id) values (new.behandling_id);
    END IF;
    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER BEHANDLING_VERSJON_FK_BUMPER_TRIGGER
    AFTER INSERT
    ON SKAL_TIL_AAP_AVKLARING
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
EXECUTE FUNCTION BEHANDLING_VERSJON_FK_BUMPER();

CREATE CONSTRAINT TRIGGER BEHANDLING_VERSJON_FK_BUMPER_TRIGGER
    AFTER INSERT
    ON KATEGORIAVKLARING
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
EXECUTE FUNCTION BEHANDLING_VERSJON_FK_BUMPER();

CREATE CONSTRAINT TRIGGER BEHANDLING_VERSJON_FK_BUMPER_TRIGGER
    AFTER INSERT
    ON DIGITALISERINGSAVKLARING
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
EXECUTE FUNCTION BEHANDLING_VERSJON_FK_BUMPER();

CREATE CONSTRAINT TRIGGER BEHANDLING_VERSJON_FK_BUMPER_TRIGGER
    AFTER INSERT
    ON SAKSNUMMER_AVKLARING
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
EXECUTE FUNCTION BEHANDLING_VERSJON_FK_BUMPER();