ALTER INDEX BARE_EN_AKTIV RENAME TO BARE_EN_AKTIV_SAKSAVKLARING_PÅ_BEHANDLING;

ALTER TABLE SKAL_TIL_AAP_AVKLARING
    RENAME TO TEMAVURDERING;

CREATE TABLE TEMAVURDERING_GRUNNLAG
(
    ID               BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID    BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    TEMAVURDERING_ID BIGINT                                 NOT NULL REFERENCES TEMAVURDERING (ID),
    AKTIV            BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX BARE_EN_AKTIV_TEMAAVKLARING_PÅ_BEHANDLING ON TEMAVURDERING_GRUNNLAG (BEHANDLING_ID, AKTIV) WHERE AKTIV;

INSERT INTO TEMAVURDERING_GRUNNLAG (BEHANDLING_ID, TEMAVURDERING_ID)
SELECT BEHANDLING_ID, ID
FROM TEMAVURDERING ON CONFLICT (BEHANDLING_ID, AKTIV) WHERE AKTIV DO UPDATE SET AKTIV = FALSE ;

ALTER TABLE TEMAVURDERING
    DROP COLUMN behandling_id;