CREATE TABLE SAKSVURDERING_GRUNNLAG
(
    ID                      BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID           BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    SAKSNUMMER_AVKLARING_ID BIGINT                                 NOT NULL REFERENCES SAKSNUMMER_AVKLARING (ID),
    AKTIV                   BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID           TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX BARE_EN_AKTIV ON SAKSVURDERING_GRUNNLAG (BEHANDLING_ID, AKTIV) WHERE AKTIV;

INSERT INTO SAKSVURDERING_GRUNNLAG (BEHANDLING_ID, SAKSNUMMER_AVKLARING_ID) SELECT BEHANDLING_ID, ID FROM SAKSNUMMER_AVKLARING;

ALTER TABLE saksnummer_avklaring DROP COLUMN behandling_id;