CREATE TABLE JOARK_HENDELSE
(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    HENDELSESID VARCHAR(255) NOT NULL UNIQUE,
    HENDELSE text NOT NULL
);

CREATE INDEX JOARK_HENDELSE_HENDELSESID_INDEX ON JOARK_HENDELSE(HENDELSESID);
