TRUNCATE TABLE KATEGORIAVKLARING_GRUNNLAG;

ALTER TABLE KATEGORIAVKLARING_GRUNNLAG ADD COLUMN BEHANDLING_ID BIGINT NOT NULL REFERENCES BEHANDLING(ID);

CREATE UNIQUE INDEX BARE_EN_AKTIV_KATEGORIAVKLARING_PÅ_BEHANDLING ON KATEGORIAVKLARING_GRUNNLAG (BEHANDLING_ID, AKTIV) WHERE AKTIV;

INSERT INTO KATEGORIAVKLARING_GRUNNLAG (BEHANDLING_ID, KATEGORIAVKLARING_ID)
SELECT BEHANDLING_ID, ID
FROM KATEGORIAVKLARING ON CONFLICT (BEHANDLING_ID, AKTIV) WHERE AKTIV DO UPDATE SET AKTIV = FALSE ;

ALTER TABLE KATEGORIAVKLARING DROP COLUMN BEHANDLING_ID