ALTER TABLE PERSON_IDENT
    ADD COLUMN primaer BOOLEAN NOT NULL default true;

CREATE UNIQUE INDEX UIDX_PERSON_IDENT_PRIMARY ON PERSON_IDENT (person_id) WHERE (primaer = TRUE);
CREATE UNIQUE INDEX UIDX_PERSON_IDENT_DUPLIKAT ON PERSON_IDENT (ident);

ALTER TABLE person_ident
    ALTER COLUMN primaer DROP default;