CREATE TABLE STRUKTURERINGAVKLARING_GRUNNLAG
(
    ID                          BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID               BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    DIGITALISERINGSAVKLARING_ID BIGINT                                 NOT NULL REFERENCES DIGITALISERINGSAVKLARING (ID),
    AKTIV                       BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID               TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX BARE_EN_AKTIV_STRUKTURERINGAVKLARING_PÅ_BEHANDLING ON STRUKTURERINGAVKLARING_GRUNNLAG (BEHANDLING_ID, AKTIV) WHERE AKTIV;

INSERT INTO STRUKTURERINGAVKLARING_GRUNNLAG (BEHANDLING_ID, DIGITALISERINGSAVKLARING_ID)
SELECT BEHANDLING_ID, ID
FROM DIGITALISERINGSAVKLARING
ON CONFLICT (BEHANDLING_ID, AKTIV)
WHERE AKTIV DO
UPDATE
SET AKTIV = FALSE;

ALTER TABLE DIGITALISERINGSAVKLARING
    DROP COLUMN behandling_id;