
ALTER TABLE DIGITALISERINGSAVKLARING ADD COLUMN KATEGORI VARCHAR(50);

UPDATE DIGITALISERINGSAVKLARING
    SET KATEGORI = tmp_kategori.kategori
FROM (SELECT STRUKTURERINGAVKLARING_GRUNNLAG.DIGITALISERINGSAVKLARING_ID, kategori FROM KATEGORIAVKLARING_GRUNNLAG
        JOIN KATEGORIAVKLARING ON KATEGORIAVKLARING_ID = KATEGORIAVKLARING.ID
        JOIN STRUKTURERINGAVKLARING_GRUNNLAG ON STRUKTURERINGAVKLARING_GRUNNLAG.behandling_id = KATEGORIAVKLARING_GRUNNLAG.behandling_id
         WHERE KATEGORIAVKLARING_GRUNNLAG.AKTIV
            AND STRUKTURERINGAVKLARING_GRUNNLAG.AKTIV) as tmp_kategori
    WHERE DIGITALISERINGSAVKLARING.id = tmp_kategori.DIGITALISERINGSAVKLARING_ID;

DROP TABLE KATEGORIAVKLARING_GRUNNLAG cascade;

ALTER TABLE DIGITALISERINGSAVKLARING ALTER COLUMN KATEGORI SET NOT NULL;
ALTER TABLE DIGITALISERINGSAVKLARING ALTER COLUMN strukturert_dokument DROP NOT NULL;

ALTER TABLE STRUKTURERINGAVKLARING_GRUNNLAG RENAME TO DIGITALISERINGSVURDERING_GRUNNLAG;