DROP INDEX UIDX_OPPGAVE_STATUS_SAK_BEHANDLING_TYPE;

CREATE UNIQUE INDEX UIDX_JOBB_STATUS_SAK_BEHANDLING_TYPE ON JOBB (TYPE, SAK_ID, BEHANDLING_ID) WHERE (
    STATUS IN ('KLAR', 'FEILET') AND sak_id is not null AND behandling_id is not null);