CREATE TABLE SKAL_TIL_AAP_AVKLARING
(
    ID            BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    SKAL_TIL_AAP  BOOLEAN                                NOT NULL,
    TIDSSTEMPEL   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE KATEGORIAVKLARING
(
    ID            BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    KATEGORI      VARCHAR(50)                            NOT NULL,
    TIDSSTEMPEL   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE DIGITALISERINGSAVKLARING
(
    ID                   BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID        BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    STRUKTURERT_DOKUMENT TEXT                                   NOT NULL,
    TIDSSTEMPEL          TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
)