ALTER TABLE JOURNALPOST
    ADD COLUMN TITTEL TEXT;

ALTER TABLE DOKUMENT
    ADD COLUMN TITTEL TEXT;

CREATE TABLE AVSENDERMOTTAKER
(
    ID             BIGSERIAL NOT NULL PRIMARY KEY,
    JOURNALPOST_ID BIGINT    NOT NULL REFERENCES JOURNALPOST (ID),
    IDENT          TEXT,
    IDENT_TYPE     TEXT,
    NAVN           TEXT
);

CREATE INDEX IDX_AVSENDERMOTTAKER_JOURNALPOST_ID ON AVSENDERMOTTAKER (JOURNALPOST_ID);
