CREATE TABLE VURDER_OPPRETTELSE_AV_SAK_VURDERING
(
    ID            BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    VALG          VARCHAR(50),
    BEGRUNNELSE   TEXT,
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    TIDSSTEMPEL   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_VURDER_OPPRETTELSE_AV_SAK_BEHANDLING ON VURDER_OPPRETTELSE_AV_SAK_VURDERING (BEHANDLING_ID);

