create table AVKLAR_FORDELING_VURDERING
(
    ID                BIGSERIAL                 NOT NULL PRIMARY KEY ,
    VURDERT_AV        TEXT                      NOT NULL,
    OPPRETTET_TID     TIMESTAMP(3)              NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FAGSYSTEM         TEXT                      NOT NULL
);


CREATE TABLE AVKLAR_FORDELING_GRUNNLAG
(
    ID                            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID                 BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    AVKLAR_FORDELING_VURDERING_ID BIGINT                                 NOT NULL REFERENCES AVKLAR_FORDELING_VURDERING (ID),
    AKTIV                         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID                 TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);


CREATE UNIQUE INDEX UIDX_AVKLAR_FORDELING_GRUNNLAG ON AVKLAR_FORDELING_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);
