CREATE INDEX INNHENTEDE_SAKER_FOR_BEHANDLING_BEHANDLING_ID_OPPRETTET_INDEX
    ON INNHENTEDE_SAKER_FOR_BEHANDLING (BEHANDLING_ID, OPPRETTET DESC);

CREATE INDEX SAKER_PAA_BEHANDLING_INNHENTEDE_SAKER_FOR_BEHANDLING_ID_INDEX
    ON SAKER_PAA_BEHANDLING (INNHENTEDE_SAKER_FOR_BEHANDLING_ID);
