

CREATE TABLE INNHENTEDE_SAKER_FOR_BEHANDLING (
    ID BIGSERIAL PRIMARY KEY ,
    OPPRETTET TIMESTAMP(3) default current_timestamp,
    BEHANDLING_ID BIGINT REFERENCES BEHANDLING(ID)
);

CREATE TABLE SAKER_PAA_BEHANDLING (
    ID BIGSERIAL PRIMARY KEY,
    INNHENTEDE_SAKER_FOR_BEHANDLING_ID BIGINT REFERENCES INNHENTEDE_SAKER_FOR_BEHANDLING(ID),
    SAKSNUMMER VARCHAR(255) NOT NULL,
    PERIODE DATERANGE
);