CREATE TABLE SAKSNUMMER_AVKLARING
(
    ID            BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    SAKSNUMMER    VARCHAR(25),
    OPPRETT_NY    BOOLEAN                                NOT NULL,
    TIDSSTEMPEL   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE BEHANDLING
    DROP COLUMN SAKSNUMMER;

CREATE CONSTRAINT TRIGGER BEHANDLING_VERSJON_FK_DIGITALISERING_BUMPER_TRIGGER
    AFTER INSERT
    ON SAKSNUMMER_AVKLARING
    FOR EACH ROW
EXECUTE FUNCTION BEHANDLING_VERSJON_FK_BUMPER();