

ALTER TABLE SONINGSFORHOLD_VURDERING
    ADD COLUMN BEGRUNNELSE TEXT;

UPDATE SONINGSFORHOLD_VURDERING
    SET BEGRUNNELSE = BEGRUNNELSE_FOR_SONING_UTENFOR_FENGSEL
    WHERE BEGRUNNELSE_FOR_SONING_UTENFOR_FENGSEL is not null;

UPDATE SONINGSFORHOLD_VURDERING
SET BEGRUNNELSE = BEGRUNNELSE_FOR_SONING_UTENFOR_ANSTALT
WHERE BEGRUNNELSE_FOR_SONING_UTENFOR_ANSTALT is not null;

ALTER TABLE SONINGSFORHOLD_VURDERING DROP COLUMN BEGRUNNELSE_FOR_SONING_UTENFOR_FENGSEL,
    DROP COLUMN BEGRUNNELSE_FOR_SONING_UTENFOR_ANSTALT;