CREATE TABLE KATEGORIAVKLARING_GRUNNLAG
(
    ID               BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID    BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    KATEGORIAVKLARING_ID BIGINT                                 NOT NULL REFERENCES KATEGORIAVKLARING (ID),
    AKTIV            BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX BARE_EN_AKTIV_KATEGORIAVKLARING_PÅ_BEHANDLING ON KATEGORIAVKLARING_GRUNNLAG (BEHANDLING_ID, AKTIV) WHERE AKTIV;

INSERT INTO KATEGORIAVKLARING_GRUNNLAG (BEHANDLING_ID, KATEGORIAVKLARING_ID)
SELECT BEHANDLING_ID, ID
FROM KATEGORIAVKLARING ON CONFLICT (BEHANDLING_ID, AKTIV) WHERE AKTIV DO UPDATE SET AKTIV = FALSE ;

ALTER TABLE KATEGORIAVKLARING_GRUNNLAG
    DROP COLUMN behandling_id;