-- give access to IAM users (GCP)
CREATE EXTENSION IF NOT EXISTS BTREE_GIST;
GRANT ALL ON ALL TABLES IN SCHEMA PUBLIC TO CLOUDSQLIAMUSER;

CREATE TABLE PERSON
(
    ID        BIGSERIAL NOT NULL PRIMARY KEY,
    REFERANSE UUID      NOT NULL UNIQUE
);
CREATE INDEX IDX_PERSON_REFERANSE ON PERSON (REFERANSE);

CREATE TABLE PERSON_IDENT
(
    ID        BIGSERIAL          NOT NULL PRIMARY KEY,
    PERSON_ID BIGINT             NOT NULL REFERENCES PERSON (ID),
    IDENT     VARCHAR(19) UNIQUE NOT NULL
);

CREATE INDEX IDX_PERSON_IDENT_IDENT ON PERSON_IDENT (IDENT);

CREATE TABLE SAK
(
    ID                BIGSERIAL                              NOT NULL PRIMARY KEY,
    SAKSNUMMER        VARCHAR(19)                            NOT NULL,
    PERSON_ID         BIGINT                                 NOT NULL REFERENCES PERSON (ID),
    RETTIGHETSPERIODE DATERANGE                              NOT NULL,
    STATUS            VARCHAR(100)                           NOT NULL,
    VERSJON           BIGINT       DEFAULT 0                 NOT NULL,
    OPPRETTET_TID     TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- avhenger av: "CREATE EXTENSION IF NOT EXISTS BTREE_GIST;" som superbruker

ALTER TABLE SAK
    ADD CONSTRAINT SAK_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        PERSON_ID WITH =,
        RETTIGHETSPERIODE WITH &&
        );

CREATE INDEX IDX_SAK_SAKSNUMMER ON SAK (SAKSNUMMER);
CREATE INDEX IDX_SAK_PERSON ON SAK (PERSON_ID);

CREATE SEQUENCE IF NOT EXISTS SEQ_SAKSNUMMER INCREMENT BY 50 MINVALUE 10000000;

CREATE TABLE BEHANDLING
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    SAK_ID        BIGINT                                 NOT NULL REFERENCES SAK (ID),
    REFERANSE     UUID UNIQUE                            NOT NULL,
    STATUS        VARCHAR(100)                           NOT NULL,
    TYPE          VARCHAR(100)                           NOT NULL,
    VERSJON       BIGINT       DEFAULT 0                 NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_BEHANDLING_REFERANSE ON BEHANDLING (REFERANSE);
CREATE INDEX IDX_BEHANDLING_SAK_TID ON BEHANDLING (SAK_ID, OPPRETTET_TID);

CREATE TABLE AVKLARINGSBEHOV
(
    ID              BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID   BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    DEFINISJON      VARCHAR(50)                            NOT NULL,
    FUNNET_I_STEG   VARCHAR(50)                            NOT NULL,
    KREVER_TO_TRINN BOOLEAN,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_AVKLARINGSBEHOV_DEFINISJON ON AVKLARINGSBEHOV (DEFINISJON);
CREATE UNIQUE INDEX IDX_AVKLARINGSBEHOV_BEHANDLING_DEFINISJON ON AVKLARINGSBEHOV (BEHANDLING_ID, DEFINISJON);

CREATE INDEX IDX_AVKLARINGSBEHOV_TID ON AVKLARINGSBEHOV (OPPRETTET_TID);
CREATE TABLE AVKLARINGSBEHOV_ENDRING
(
    ID                        BIGSERIAL                              NOT NULL PRIMARY KEY,
    AVKLARINGSBEHOV_ID        BIGINT                                 NOT NULL REFERENCES AVKLARINGSBEHOV (ID),
    STATUS                    VARCHAR(50)                            NOT NULL,
    BEGRUNNELSE               TEXT,
    FRIST                     DATE,
    AARSAK_TIL_RETUR          VARCHAR(50),
    AARSAK_TIL_RETUR_FRITEKST TEXT,
    OPPRETTET_AV              VARCHAR(100)                           NOT NULL,
    OPPRETTET_TID             TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_AVKLARINGSBEHOV_ENDRING_TID ON AVKLARINGSBEHOV_ENDRING (OPPRETTET_TID);

CREATE TABLE AVKLARINGSBEHOV_ENDRING_AARSAK
(
    ID                        BIGSERIAL                              NOT NULL PRIMARY KEY,
    ENDRING_ID                BIGINT                                 NOT NULL REFERENCES AVKLARINGSBEHOV_ENDRING (ID),
    AARSAK_TIL_RETUR          VARCHAR(50)                            NOT NULL,
    AARSAK_TIL_RETUR_FRITEKST TEXT,
    OPPRETTET_AV              VARCHAR(100)                           NOT NULL,
    OPPRETTET_TID             TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_AVKLARINGSBEHOV_ENDRING_AARSAK_TID ON AVKLARINGSBEHOV_ENDRING_AARSAK (OPPRETTET_TID);
CREATE INDEX IDX_AVKLARINGSBEHOV_ENDRING_AARSAK_TID_2 ON AVKLARINGSBEHOV_ENDRING_AARSAK (ENDRING_ID, OPPRETTET_TID);

CREATE TABLE STEG_HISTORIKK
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    STEG          VARCHAR(50)                            NOT NULL,
    STATUS        VARCHAR(50)                            NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX UIDX_STEG_HISTORIKK ON STEG_HISTORIKK (BEHANDLING_ID) WHERE (AKTIV = TRUE);

--
CREATE TABLE OPPGAVE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    STATUS        VARCHAR(50)  DEFAULT 'KLAR'            NOT NULL,
    TYPE          VARCHAR(50)                            NOT NULL,
    SAK_ID        BIGINT                                 NULL REFERENCES SAK (ID),
    BEHANDLING_ID BIGINT                                 NULL REFERENCES BEHANDLING (ID),
    NESTE_KJORING TIMESTAMP(3)                           NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_OPPGAVE_STATUS ON OPPGAVE (STATUS, SAK_ID, BEHANDLING_ID, NESTE_KJORING);
-- Legger inn en unik index per type for en sak+behandling for åpne oppgaver
CREATE UNIQUE INDEX UIDX_OPPGAVE_STATUS_SAK_BEHANDLING_TYPE ON OPPGAVE (TYPE, SAK_ID, BEHANDLING_ID) WHERE (STATUS IN ('KLAR', 'FEILET'));

CREATE TABLE OPPGAVE_HISTORIKK
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPGAVE_ID    BIGINT                                 NOT NULL REFERENCES OPPGAVE (ID),
    STATUS        VARCHAR(50)                            NOT NULL,
    FEILMELDING   TEXT                                   NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_OPPGAVE_HISTORIKK_STATUS ON OPPGAVE_HISTORIKK (OPPGAVE_ID, STATUS);
