-- MOTTATT DOKUMENT
CREATE TABLE MOTTATT_DOKUMENT
(
    ID                   BIGSERIAL                              NOT NULL PRIMARY KEY,
    SAK_ID               BIGINT                                 NOT NULL REFERENCES SAK (ID),
    BEHANDLING_ID        BIGINT                                 NULL REFERENCES BEHANDLING (ID),
    JOURNALPOST          VARCHAR(25)                            NOT NULL,
    MOTTATT_TID          TIMESTAMP(3)                           NOT NULL,
    TYPE                 VARCHAR(50)                            NOT NULL,
    STATUS               VARCHAR(50)                            NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    strukturert_dokument TEXT                                   NULL
);
CREATE INDEX IDX_MOTTATT_DOKUMENT_1 ON MOTTATT_DOKUMENT (SAK_ID, TYPE, STATUS);
CREATE INDEX IDX_MOTTATT_DOKUMENT_2 ON MOTTATT_DOKUMENT (SAK_ID, BEHANDLING_ID);
CREATE INDEX IDX_MOTTATT_DOKUMENT_3 ON MOTTATT_DOKUMENT (SAK_ID, MOTTATT_TID);
CREATE INDEX IDX_MOTTATT_DOKUMENT_4 ON MOTTATT_DOKUMENT (SAK_ID, TYPE);

CREATE UNIQUE INDEX UIDX_MOTTATT_DOKUMENT_SAK_JOURNALPOST ON MOTTATT_DOKUMENT (SAK_ID, JOURNALPOST);


-- PLIKTKORT
CREATE TABLE SAK_PLIKTKORT
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    JOURNALPOST   VARCHAR(25)                            NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_SAK_PLIKTKORT ON SAK_PLIKTKORT (JOURNALPOST);

CREATE TABLE SAK_PLIKTKORT_PERIODE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    PLIKTKORT_ID  BIGINT                                 NOT NULL REFERENCES SAK_PLIKTKORT (ID),
    PERIODE       DATERANGE                              NOT NULL,
    TIMER_ARBEID  NUMERIC(5, 1)                          NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE SAK_PLIKTKORT_PERIODE
    ADD CONSTRAINT SAK_PLIKTKORT_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        PLIKTKORT_ID WITH =,
        PERIODE WITH &&
        );

CREATE TABLE PLIKTKORTENE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE PLIKTKORT
(
    ID              BIGSERIAL                              NOT NULL PRIMARY KEY,
    PLIKTKORTENE_ID BIGINT                                 NOT NULL REFERENCES PLIKTKORTENE (ID),
    JOURNALPOST     VARCHAR(25)                            NOT NULL,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IDX_PLIKTKORT ON PLIKTKORT (JOURNALPOST);

CREATE TABLE PLIKTKORT_PERIODE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    PLIKTKORT_ID  BIGINT                                 NOT NULL REFERENCES PLIKTKORT (ID),
    PERIODE       DATERANGE                              NOT NULL,
    TIMER_ARBEID  NUMERIC(5, 1)                          NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE PLIKTKORT_PERIODE
    ADD CONSTRAINT PLIKTKORT_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        PLIKTKORT_ID WITH =,
        PERIODE WITH &&
        );

CREATE TABLE PLIKKORT_GRUNNLAG
(
    ID              BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID   BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    PLIKTKORTENE_ID BIGINT                                 NOT NULL REFERENCES PLIKTKORTENE (ID),
    AKTIV           BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID   TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_PLIKKORT_GRUNNLAG_BEHANDLING_ID ON PLIKKORT_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);
