CREATE TABLE INNKOMMENDE_JOURNALPOST
(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    JOURNALPOST_ID BIGINT NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STATUS VARCHAR(100) NOT NULL
);

CREATE TABLE REGELSETT_RESULTAT(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    INNKOMMENDE_JOURNALPOST BIGINT NOT NULL REFERENCES INNKOMMENDE_JOURNALPOST(ID),
    SYSTEM_NAVN VARCHAR(100) NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE REGEL_EVALUERING (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    REGEL_RESULTAT_ID BIGINT NOT NULL REFERENCES REGELSETT_RESULTAT(ID),
    REGEL_NAVN VARCHAR(100) NOT NULL,
    RESULTAT BOOLEAN NOT NULL
);