-- ARBEIDSEVNE GRUNNLAG

CREATE TABLE ARBEIDSEVNE
(
    ID                   BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEGRUNNELSE          TEXT                                   NOT NULL,
    ANDEL_AV_NEDSETTELSE SMALLINT                               NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE ARBEIDSEVNE_GRUNNLAG
(
    ID             BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID  BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    ARBEIDSEVNE_ID BIGINT                                 NOT NULL REFERENCES ARBEIDSEVNE (ID),
    AKTIV          BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID  TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_ARBEIDSEVNE_GRUNNLAG_BEHANDLING_ID ON ARBEIDSEVNE_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- BISTAND

CREATE TABLE BISTAND
(
    ID                   BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEGRUNNELSE          TEXT                                   NOT NULL,
    ER_BEHOV_FOR_BISTAND BOOLEAN                                NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BISTAND_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    BISTAND_ID    BIGINT                                 NOT NULL REFERENCES BISTAND (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IDX_BISTAND_GRUNNLAG_BEHANDLING_ID ON BISTAND_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- FRITAK MELDEPLIKT

CREATE TABLE MELDEPLIKT_FRITAK
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE MELDEPLIKT_FRITAK_VURDERING
(
    ID            BIGSERIAL NOT NULL PRIMARY KEY,
    MELDEPLIKT_ID BIGINT    NOT NULL REFERENCES MELDEPLIKT_FRITAK (ID),
    PERIODE       DATERANGE NOT NULL,
    BEGRUNNELSE   TEXT      NOT NULL,
    HAR_FRITAK    BOOLEAN   NOT NULL
);

CREATE INDEX IDX_MELDEPLIKT_FRITAK_VURDERING_MELDEPLIKT_ID ON MELDEPLIKT_FRITAK_VURDERING (MELDEPLIKT_ID);

CREATE TABLE MELDEPLIKT_FRITAK_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    MELDEPLIKT_ID BIGINT                                 NOT NULL REFERENCES MELDEPLIKT_FRITAK (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IDX_MELDEPLIKT_FRITAK_GRUNNLAG_BEHANDLING_ID ON MELDEPLIKT_FRITAK_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- STUDENT

CREATE TABLE STUDENT_VURDERING
(
    ID           BIGSERIAL NOT NULL PRIMARY KEY,
    BEGRUNNELSE  TEXT      NULL,
    OPPFYLT      BOOLEAN   NOT NULL,
    AVBRUTT_DATO DATE      NULL
);

CREATE TABLE STUDENT_VURDERING_DOKUMENTER
(
    ID           BIGSERIAL   NOT NULL PRIMARY KEY,
    VURDERING_ID BIGINT      NOT NULL REFERENCES STUDENT_VURDERING,
    JOURNALPOST  VARCHAR(25) NOT NULL
);
CREATE UNIQUE INDEX UIDX_STUDENT_VURDERING_DOKUMENTER ON STUDENT_VURDERING_DOKUMENTER (JOURNALPOST, VURDERING_ID);

CREATE TABLE STUDENT_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    STUDENT_ID    BIGINT                                 NULL REFERENCES STUDENT_VURDERING (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_STUDENT_GRUNNLAG_HISTORIKK ON STUDENT_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);
