-- ARBEIDSEVNE GRUNNLAG

CREATE TABLE ARBEIDSEVNE
(
    ID                   BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEGRUNNELSE          TEXT                                   NOT NULL,
    ANDEL_AV_NEDSETTELSE SMALLINT                               NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE ARBEIDSEVNE_GRUNNLAG
(
    ID             BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID  BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    ARBEIDSEVNE_ID BIGINT                                 NOT NULL REFERENCES ARBEIDSEVNE (ID),
    AKTIV          BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID  TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_ARBEIDSEVNE_GRUNNLAG_BEHANDLING_ID ON ARBEIDSEVNE_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);
