-- BARNETILLEGG GRUNNLAG

CREATE TABLE BARNETILLEGG_PERIODER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BARNETILLEGG_PERIODE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES BARNETILLEGG_PERIODER (ID),
    PERIODE       DATERANGE                              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE BARNETILLEGG_PERIODE
    ADD CONSTRAINT BARNETILLEGG_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        PERIODER_ID WITH =,
        PERIODE WITH &&
        );

CREATE TABLE BARN_TILLEGG
(
    ID                      BIGSERIAL   NOT NULL PRIMARY KEY,
    IDENT                   VARCHAR(19) NOT NULL,
    BARNETILLEGG_PERIODE_ID BIGINT      NOT NULL REFERENCES BARNETILLEGG_PERIODE (ID)
);

CREATE TABLE BARNETILLEGG_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES BARNETILLEGG_PERIODER (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_BARNETILLEGG_GRUNNLAG_BEHANDLING_ID ON BARNETILLEGG_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- BEREGNINGSGRUNNLAG

CREATE TABLE BEREGNING
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BEREGNING_UFORE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEREGNING_ID  BIGINT                                 NOT NULL REFERENCES BEREGNING (ID),
    TYPE          TEXT                                   NOT NULL,
    GJELDENDE     BOOLEAN                                NOT NULL,
    G_UNIT        NUMERIC(21, 10)                        NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_BEREGNING_UFORE_BEHANDLING_ID ON BEREGNING_UFORE (BEREGNING_ID) WHERE (GJELDENDE = TRUE);
CREATE UNIQUE INDEX UIDX_BEREGNING_UFORE_TYPE ON BEREGNING_UFORE (BEREGNING_ID, TYPE);

CREATE TABLE BEREGNING_HOVED
(
    ID                 BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEREGNING_UFORE_ID BIGINT                                 NOT NULL REFERENCES BEREGNING_UFORE (ID),
    G_UNIT             NUMERIC(21, 10)                        NOT NULL,
    OPPRETTET_TID      TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BEREGNING_YRKESSKADE
(
    ID                 BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEREGNING_HOVED_ID BIGINT                                 NOT NULL REFERENCES BEREGNING_HOVED (ID),
    G_UNIT             NUMERIC(21, 10)                        NOT NULL,
    OPPRETTET_TID      TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BEREGNINGSGRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    BEREGNING_ID  BIGINT                                 NOT NULL REFERENCES BEREGNING (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_BEREGNINGSGRUNNLAG_BEHANDLING_ID ON BEREGNINGSGRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- UNDERVEIS GRUNNLAG

CREATE TABLE UNDERVEIS_PERIODER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE UNDERVEIS_PERIODE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES UNDERVEIS_PERIODER (ID),
    PERIODE       DATERANGE                              NOT NULL,
    TIMER_ARBEID  NUMERIC(5, 1)                          NULL,
    UTFALL        VARCHAR(50)                            NOT NULL,
    AVSLAGSARSAK  VARCHAR(50)                            NULL,
    GRENSEVERDI   SMALLINT                               NOT NULL,
    GRADERING     SMALLINT                               NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE UNDERVEIS_PERIODE
    ADD CONSTRAINT UNDERVEIS_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        PERIODER_ID WITH =,
        PERIODE WITH &&
        );

CREATE TABLE UNDERVEIS_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    PERIODER_ID   BIGINT                                 NOT NULL REFERENCES UNDERVEIS_PERIODER (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_UNDERVEIS_GRUNNLAG_BEHANDLING_ID ON UNDERVEIS_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- VILKÅRSRESULTAT

CREATE TABLE VILKAR_RESULTAT
(
    ID            BIGSERIAL            NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT               NOT NULL REFERENCES BEHANDLING (ID),
    AKTIV         BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE UNIQUE INDEX UIDX_VILKAR_RESULTAT_HISTORIKK ON VILKAR_RESULTAT (BEHANDLING_ID) WHERE (AKTIV = TRUE);

CREATE TABLE VILKAR
(
    ID          BIGSERIAL   NOT NULL PRIMARY KEY,
    TYPE        VARCHAR(50) NOT NULL,
    RESULTAT_ID BIGINT      NOT NULL REFERENCES VILKAR_RESULTAT (ID)
);

CREATE UNIQUE INDEX UIDX_VILKAR ON VILKAR (RESULTAT_ID, TYPE);

CREATE TABLE VILKAR_PERIODE
(
    ID                BIGSERIAL     NOT NULL PRIMARY KEY,
    VILKAR_ID         BIGINT        NOT NULL REFERENCES VILKAR (ID),
    PERIODE           DATERANGE     NOT NULL,
    UTFALL            VARCHAR(50)   NOT NULL,
    MANUELL_VURDERING BOOLEAN       NOT NULL,
    BEGRUNNELSE       TEXT          NULL,
    INNVILGELSESARSAK VARCHAR(100)  NULL,
    AVSLAGSARSAK      VARCHAR(100)  NULL,
    FAKTAGRUNNLAG     VARCHAR(4000) NULL,
    VERSJON           VARCHAR(100)  NOT NULL
);
CREATE INDEX IDX_VILKAR_PERIODE_PERIODE ON VILKAR_PERIODE (VILKAR_ID, PERIODE);
ALTER TABLE VILKAR_PERIODE
    ADD CONSTRAINT VILKAR_PERIODE_IKKE_OVERLAPP_PERIODE EXCLUDE USING GIST (
        VILKAR_ID WITH =,
        PERIODE WITH &&
        );
