-- INNTEKT GRUNNLAG

CREATE TABLE INNTEKTER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE INNTEKT
(
    ID         BIGSERIAL      NOT NULL PRIMARY KEY,
    INNTEKT_ID BIGINT         NOT NULL REFERENCES INNTEKTER (ID),
    AR         smallint       NOT NULL,
    BELOP      NUMERIC(19, 2) NOT NULL
);

CREATE INDEX IDX_INNTEKT_INNTEKTER_ID ON INNTEKT (INNTEKT_ID);

CREATE TABLE INNTEKT_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    INNTEKT_ID    BIGINT                                 NOT NULL REFERENCES INNTEKTER (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_INNTEKT_GRUNNLAG_BEHANDLING_ID ON INNTEKT_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- PERSONOPPLYSNINGER

CREATE TABLE PERSONOPPLYSNING
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    FODSELSDATO   DATE                                   NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE PERSONOPPLYSNING_GRUNNLAG
(
    ID                  BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID       BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    PERSONOPPLYSNING_ID BIGINT                                 NOT NULL REFERENCES PERSONOPPLYSNING (ID),
    AKTIV               BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID       TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IDX_PERSONOPPLYSNING_BEHANDLING_ID ON PERSONOPPLYSNING_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);
