-- INNTEKT GRUNNLAG

CREATE TABLE INNTEKTER
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE INNTEKT
(
    ID         BIGSERIAL      NOT NULL PRIMARY KEY,
    INNTEKT_ID BIGINT         NOT NULL REFERENCES INNTEKTER (ID),
    AR         SMALLINT       NOT NULL,
    BELOP      NUMERIC(19, 2) NOT NULL
);

CREATE INDEX IDX_INNTEKT_INNTEKTER_ID ON INNTEKT (INNTEKT_ID);

CREATE TABLE INNTEKT_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    INNTEKT_ID    BIGINT                                 NOT NULL REFERENCES INNTEKTER (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_INNTEKT_GRUNNLAG_BEHANDLING_ID ON INNTEKT_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- INSTUTSJONSOPPHOLD GRUNNLAG
CREATE TABLE OPPHOLD_PERSON
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE OPPHOLD_GRUNNLAG
(
    ID                BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID     BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    OPPHOLD_PERSON_ID BIGINT                                 NOT NULL REFERENCES OPPHOLD_PERSON (ID),
    AKTIV             BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID     TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IDX_OPPHOLD_BEHANDLING_ID ON OPPHOLD_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

CREATE TABLE OPPHOLD
(
    ID                BIGSERIAL  NOT NULL PRIMARY KEY,
    OPPHOLD_PERSON_ID BIGINT     NOT NULL REFERENCES OPPHOLD_PERSON (ID),
    INSTITUSJONSTYPE  TEXT       NOT NULL,
    KATEGORI          TEXT       NOT NULL,
    ORGNR             VARCHAR(9) NOT NULL,
    PERIODE           DATERANGE  NOT NULL
);

-- PERSONOPPLYSNINGER

CREATE TABLE PERSONOPPLYSNING
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    FODSELSDATO   DATE                                   NOT NULL,
    DODSDATO      DATE         DEFAULT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE PERSONOPPLYSNING_GRUNNLAG
(
    ID                  BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID       BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    PERSONOPPLYSNING_ID BIGINT                                 NOT NULL REFERENCES PERSONOPPLYSNING (ID),
    AKTIV               BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID       TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BARNOPPLYSNING_GRUNNLAG_BARNOPPLYSNING
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE BARNOPPLYSNING
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    IDENT         VARCHAR(11)                            NOT NULL,
    FODSELSDATO   DATE                                   NOT NULL,
    DODSDATO      DATE         DEFAULT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    BGB_ID        BIGINT                                 NOT NULL REFERENCES BARNOPPLYSNING_GRUNNLAG_BARNOPPLYSNING (ID)

);

CREATE TABLE BARNOPPLYSNING_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    BGB_ID        BIGINT                                 NOT NULL REFERENCES BARNOPPLYSNING_GRUNNLAG_BARNOPPLYSNING (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IDX_PERSONOPPLYSNING_BEHANDLING_ID ON PERSONOPPLYSNING_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- UFØRE GRUNNLAG

CREATE TABLE UFORE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    UFOREGRAD     SMALLINT                               NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE UFORE_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    UFORE_ID      BIGINT                                 NOT NULL REFERENCES UFORE (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_UFORE_GRUNNLAG_BEHANDLING_ID ON UFORE_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);

-- YRKESSKADEGRUNNLAG

CREATE TABLE YRKESSKADE
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE YRKESSKADE_DATO
(
    ID            BIGSERIAL NOT NULL PRIMARY KEY,
    YRKESSKADE_ID BIGINT    NOT NULL REFERENCES YRKESSKADE (ID),
    REFERANSE     TEXT      NOT NULL,
    SKADEDATO     DATE      NOT NULL
);

CREATE INDEX IDX_YRKESSKADE_DATO_GRUNNLAG_ID ON YRKESSKADE_DATO (YRKESSKADE_ID);

CREATE TABLE YRKESSKADE_GRUNNLAG
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    BEHANDLING_ID BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    YRKESSKADE_ID BIGINT                                 NOT NULL REFERENCES YRKESSKADE (ID),
    AKTIV         BOOLEAN      DEFAULT TRUE              NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX UIDX_YRKESSKADE_GRUNNLAG_BEHANDLING_ID ON YRKESSKADE_GRUNNLAG (BEHANDLING_ID) WHERE (AKTIV = TRUE);
