CREATE OR REPLACE FUNCTION BEHANDLING_VERSJON_BUMPER()
    RETURNS TRIGGER
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    NEW.VERSJON = OLD.VERSJON + 1;
    RETURN NEW;
END;
$$;

CREATE TRIGGER BEHANDLING_VERSJON_BUMPER_TRIGGER
    BEFORE UPDATE
    ON BEHANDLING
    FOR EACH ROW
EXECUTE FUNCTION BEHANDLING_VERSJON_BUMPER();

CREATE OR REPLACE FUNCTION BEHANDLING_VERSJON_FK_BUMPER()
    RETURNS TRIGGER
    LANGUAGE PLPGSQL
AS
$$
BEGIN
    UPDATE BEHANDLING
    SET VERSJON = VERSJON + 1
    WHERE ID = NEW.BEHANDLING_ID;
    RETURN NEW;
END;
$$;

CREATE CONSTRAINT TRIGGER BEHANDLING_VERSJON_FK_TEMA_BUMPER_TRIGGER
    AFTER INSERT
    ON SKAL_TIL_AAP_AVKLARING
    FROM BEHANDLING
    FOR EACH ROW
EXECUTE FUNCTION BEHANDLING_VERSJON_FK_BUMPER();

CREATE CONSTRAINT TRIGGER BEHANDLING_VERSJON_FK_KATEGORI_BUMPER_TRIGGER
    AFTER INSERT
    ON KATEGORIAVKLARING
    FROM BEHANDLING
    FOR EACH ROW
EXECUTE FUNCTION BEHANDLING_VERSJON_FK_BUMPER();

CREATE CONSTRAINT TRIGGER BEHANDLING_VERSJON_FK_DIGITALISERING_BUMPER_TRIGGER
    AFTER INSERT
    ON DIGITALISERINGSAVKLARING
    FOR EACH ROW
EXECUTE FUNCTION BEHANDLING_VERSJON_FK_BUMPER();