CREATE TABLE JOURNALPOST
(
    ID                   BIGSERIAL                              NOT NULL PRIMARY KEY,
    JOURNALPOST_ID       BIGINT                                 NOT NULL UNIQUE,
    BEHANDLING_ID        BIGSERIAL                              NOT NULL REFERENCES BEHANDLING (ID),
    PERSON_IDENT                VARCHAR(100) NULL,
    AKTOER_IDENT                VARCHAR(100) NULL,
    JOURNALFORENDE_ENHET VARCHAR(25) NULL,
    STATUS               VARCHAR(25)                            NOT NULL,
    MOTTATT_DATO         DATE                                   NOT NULL,
    OPPRETTET_TID        TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_JOURNALPOST_JOURNALPOST_ID ON JOURNALPOST (JOURNALPOST_ID);
CREATE INDEX IDX_JOURNALPOST_BEHANDLING_ID ON JOURNALPOST (BEHANDLING_ID);

CREATE TABLE DOKUMENT
(
    ID               BIGSERIAL                              NOT NULL PRIMARY KEY,
    JOURNALPOST_ID   BIGINT                                 NOT NULL REFERENCES JOURNALPOST (ID),
    DOKUMENT_INFO_ID VARCHAR(25)                            NOT NULL,
    VARIANTFORMAT    VARCHAR(20)                            NOT NULL,
    FILTYPE          VARCHAR(10)                            NOT NULL,
    BREVKODE         VARCHAR(25) NULL,
    OPPRETTET_TID    TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TITTEL           VARCHAR(100) NULL,
    IDENT            VARCHAR(100) NULL
);

CREATE INDEX IDX_DOKUMENT_JOURNALPOST_ID ON DOKUMENT (JOURNALPOST_ID);
CREATE INDEX IDX_DOKUMENT_2 ON DOKUMENT (JOURNALPOST_ID, FILTYPE, BREVKODE);