CREATE TABLE SAKSNUMMER_AVKLARING
(
    ID             BIGSERIAL PRIMARY KEY,
    BEHANDLING_ID  BIGINT                                 NOT NULL REFERENCES BEHANDLING (ID),
    SAKSNUMMER     VARCHAR(25),
    TIDSSTEMPEL    TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE BEHANDLING DROP COLUMN SAKSNUMMER;